#!/usr/bin/env python3

import json
import locale
import sys
import emails
import reports


def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.
  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  newlist = []
  sales_by_year = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

  # TODO: also handle max sales
  for item in data:
    newlist.append(item['total_sales'])
    newlist.sort()
    x = newlist[-1]
    
  for item in data:
    if item['total_sales'] == x:
      most = item['car']['car_model']
      the_car = item['car']['car_make']
    

  # TODO: also handle most popular car_year
  for item in data:
    item_year = item["car"]["car_year"]
    sales_by_year[item_year] = sales_by_year.setdefault(item_year, 0) + item['total_sales']      
  most_popular_sales = sorted(sales_by_year.items(), key=lambda item: item[1], reverse=True)
  
  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),

    'The {} {} had the most sales: {}'.format(the_car, most, x),

    'The most popular year was {} with {} sales'.format(most_popular_sales[0][0], most_popular_sales[0][1])

  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("email/car_sales.json")
  summary = process_data(data)
  print(summary)

  # TODO: turn this into a PDF report
  report_title = 'Monthly vehicle sales'
  report_path = 'email/tmp/cars.pdf'
  report_data = cars_dict_to_table(data)
  report_summary = '<br/>'.join(summary)
  reports.generate(report_path, report_title, report_summary, report_data)

  # # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  recipient = "student@example.com"
  email_title = report_title
  attch_path = report_path
  body = '\n'.join(summary)
  message = emails.generate(sender, recipient, email_title, body, attch_path)
  emails.send(message)


if __name__ == "__main__":
  main(sys.argv)
